mysql:
  image : mysql:5.7
  ports:
    - "3307:3306"
  volumes:
    - ~/db/mysql:/var/lib/mysql
    - ./config.cnf:/etc/mysql/conf.d/config.cnf
    - ./init-dump:/docker-entrypoint-initdb.d
  environment:
    TERM: xterm
    APP_ENV: dev
    MYSQL_PASSWORD: root
    MYSQL_DATABASE: test
    MYSQL_ROOT_PASSWORD: root
  container_name: mysql